% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={mini-project},
  pdfauthor={Joshua Martin (PID: A18545389)},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{mini-project}
\author{Joshua Martin (PID: A18545389)}
\date{}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}

\section{Exploratory Data Analysis}\label{exploratory-data-analysis}

\subsection{Background}\label{background}

The goal of this mini-project is for you to explore a complete analysis
using the unsupervised learning techniques covered in class. You'll
extend what you've learned by combining PCA as a preprocessing step to
clustering using data that consist of measurements of cell nuclei of
human breast masses. This expands on our RNA-Seq analysis from last day.

The data itself comes from the Wisconsin Breast Cancer Diagnostic Data
Set first reported by K. P. Benne and O. L. Mangasarian: ``Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets''.

Values in this data set describe characteristics of the cell nuclei
present in digitized images of a fine needle aspiration (FNA) of a
breast mass.

\section{Data import}\label{data-import}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read.csv}\NormalTok{(}\StringTok{"WisconsinCancer.csv"}\NormalTok{)}
\NormalTok{fna.data }\OtherTok{\textless{}{-}} \StringTok{"WisconsinCancer.csv"}
\NormalTok{wisc.df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(fna.data, }\AttributeTok{row.names=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Examine Data}\label{examine-data}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(wisc.df)}
\end{Highlighting}
\end{Shaded}

\subsection{New data frame removing first row (diagnosis
column)}\label{new-data-frame-removing-first-row-diagnosis-column}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wisc.data }\OtherTok{\textless{}{-}}\NormalTok{ wisc.df[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{]}
\FunctionTok{View}\NormalTok{(wisc.data)}
\FunctionTok{head}\NormalTok{(wisc.df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
         diagnosis radius_mean texture_mean perimeter_mean area_mean
842302           M       17.99        10.38         122.80    1001.0
842517           M       20.57        17.77         132.90    1326.0
84300903         M       19.69        21.25         130.00    1203.0
84348301         M       11.42        20.38          77.58     386.1
84358402         M       20.29        14.34         135.10    1297.0
843786           M       12.45        15.70          82.57     477.1
         smoothness_mean compactness_mean concavity_mean concave.points_mean
842302           0.11840          0.27760         0.3001             0.14710
842517           0.08474          0.07864         0.0869             0.07017
84300903         0.10960          0.15990         0.1974             0.12790
84348301         0.14250          0.28390         0.2414             0.10520
84358402         0.10030          0.13280         0.1980             0.10430
843786           0.12780          0.17000         0.1578             0.08089
         symmetry_mean fractal_dimension_mean radius_se texture_se perimeter_se
842302          0.2419                0.07871    1.0950     0.9053        8.589
842517          0.1812                0.05667    0.5435     0.7339        3.398
84300903        0.2069                0.05999    0.7456     0.7869        4.585
84348301        0.2597                0.09744    0.4956     1.1560        3.445
84358402        0.1809                0.05883    0.7572     0.7813        5.438
843786          0.2087                0.07613    0.3345     0.8902        2.217
         area_se smoothness_se compactness_se concavity_se concave.points_se
842302    153.40      0.006399        0.04904      0.05373           0.01587
842517     74.08      0.005225        0.01308      0.01860           0.01340
84300903   94.03      0.006150        0.04006      0.03832           0.02058
84348301   27.23      0.009110        0.07458      0.05661           0.01867
84358402   94.44      0.011490        0.02461      0.05688           0.01885
843786     27.19      0.007510        0.03345      0.03672           0.01137
         symmetry_se fractal_dimension_se radius_worst texture_worst
842302       0.03003             0.006193        25.38         17.33
842517       0.01389             0.003532        24.99         23.41
84300903     0.02250             0.004571        23.57         25.53
84348301     0.05963             0.009208        14.91         26.50
84358402     0.01756             0.005115        22.54         16.67
843786       0.02165             0.005082        15.47         23.75
         perimeter_worst area_worst smoothness_worst compactness_worst
842302            184.60     2019.0           0.1622            0.6656
842517            158.80     1956.0           0.1238            0.1866
84300903          152.50     1709.0           0.1444            0.4245
84348301           98.87      567.7           0.2098            0.8663
84358402          152.20     1575.0           0.1374            0.2050
843786            103.40      741.6           0.1791            0.5249
         concavity_worst concave.points_worst symmetry_worst
842302            0.7119               0.2654         0.4601
842517            0.2416               0.1860         0.2750
84300903          0.4504               0.2430         0.3613
84348301          0.6869               0.2575         0.6638
84358402          0.4000               0.1625         0.2364
843786            0.5355               0.1741         0.3985
         fractal_dimension_worst
842302                   0.11890
842517                   0.08902
84300903                 0.08758
84348301                 0.17300
84358402                 0.07678
843786                   0.12440
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diagnosis }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(wisc.df}\SpecialCharTok{$}\NormalTok{diagnosis)}
\FunctionTok{View}\NormalTok{(diagnosis)}
\end{Highlighting}
\end{Shaded}

\subsection{Confirm Structures}\label{confirm-structures}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(wisc.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
'data.frame':   569 obs. of  30 variables:
 $ radius_mean            : num  18 20.6 19.7 11.4 20.3 ...
 $ texture_mean           : num  10.4 17.8 21.2 20.4 14.3 ...
 $ perimeter_mean         : num  122.8 132.9 130 77.6 135.1 ...
 $ area_mean              : num  1001 1326 1203 386 1297 ...
 $ smoothness_mean        : num  0.1184 0.0847 0.1096 0.1425 0.1003 ...
 $ compactness_mean       : num  0.2776 0.0786 0.1599 0.2839 0.1328 ...
 $ concavity_mean         : num  0.3001 0.0869 0.1974 0.2414 0.198 ...
 $ concave.points_mean    : num  0.1471 0.0702 0.1279 0.1052 0.1043 ...
 $ symmetry_mean          : num  0.242 0.181 0.207 0.26 0.181 ...
 $ fractal_dimension_mean : num  0.0787 0.0567 0.06 0.0974 0.0588 ...
 $ radius_se              : num  1.095 0.543 0.746 0.496 0.757 ...
 $ texture_se             : num  0.905 0.734 0.787 1.156 0.781 ...
 $ perimeter_se           : num  8.59 3.4 4.58 3.44 5.44 ...
 $ area_se                : num  153.4 74.1 94 27.2 94.4 ...
 $ smoothness_se          : num  0.0064 0.00522 0.00615 0.00911 0.01149 ...
 $ compactness_se         : num  0.049 0.0131 0.0401 0.0746 0.0246 ...
 $ concavity_se           : num  0.0537 0.0186 0.0383 0.0566 0.0569 ...
 $ concave.points_se      : num  0.0159 0.0134 0.0206 0.0187 0.0188 ...
 $ symmetry_se            : num  0.03 0.0139 0.0225 0.0596 0.0176 ...
 $ fractal_dimension_se   : num  0.00619 0.00353 0.00457 0.00921 0.00511 ...
 $ radius_worst           : num  25.4 25 23.6 14.9 22.5 ...
 $ texture_worst          : num  17.3 23.4 25.5 26.5 16.7 ...
 $ perimeter_worst        : num  184.6 158.8 152.5 98.9 152.2 ...
 $ area_worst             : num  2019 1956 1709 568 1575 ...
 $ smoothness_worst       : num  0.162 0.124 0.144 0.21 0.137 ...
 $ compactness_worst      : num  0.666 0.187 0.424 0.866 0.205 ...
 $ concavity_worst        : num  0.712 0.242 0.45 0.687 0.4 ...
 $ concave.points_worst   : num  0.265 0.186 0.243 0.258 0.163 ...
 $ symmetry_worst         : num  0.46 0.275 0.361 0.664 0.236 ...
 $ fractal_dimension_worst: num  0.1189 0.089 0.0876 0.173 0.0768 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
diagnosis
  B   M 
357 212 
\end{verbatim}

\subsection{Questions:}\label{questions}

\textbf{Q1. How many observations are in this dataset?}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(wisc.df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 569  31
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(wisc.df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 569
\end{verbatim}

There are 569 observations/patients in the dataset.

\textbf{Q2. How many of the observations have a malignant diagnosis?}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
diagnosis
  B   M 
357 212 
\end{verbatim}

There are 212 malignant (M) and 357 benign (B) cases.

**Q3. How many variables/features in the data are suffixed with
\_mean?**

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{length}\NormalTok{(}\FunctionTok{grep}\NormalTok{(}\StringTok{"\_mean$"}\NormalTok{, }\FunctionTok{colnames}\NormalTok{(wisc.data)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 10
\end{verbatim}

There are 10 variables ending in \_mean.

\section{Principal Component
Analysis}\label{principal-component-analysis}

The \texttt{prcomp()} function to do PCA has a \texttt{scale=FALSE}
default. In general we always want to set this to TRUE so our analysis
is not dominated by columns/variables in our dataset that have high
standard deviation and mean when compared to others just because the
units of measurement are on different scales.

\section{Check column means and standard
deviations}\label{check-column-means-and-standard-deviations}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(wisc.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "radius_mean"             "texture_mean"           
 [3] "perimeter_mean"          "area_mean"              
 [5] "smoothness_mean"         "compactness_mean"       
 [7] "concavity_mean"          "concave.points_mean"    
 [9] "symmetry_mean"           "fractal_dimension_mean" 
[11] "radius_se"               "texture_se"             
[13] "perimeter_se"            "area_se"                
[15] "smoothness_se"           "compactness_se"         
[17] "concavity_se"            "concave.points_se"      
[19] "symmetry_se"             "fractal_dimension_se"   
[21] "radius_worst"            "texture_worst"          
[23] "perimeter_worst"         "area_worst"             
[25] "smoothness_worst"        "compactness_worst"      
[27] "concavity_worst"         "concave.points_worst"   
[29] "symmetry_worst"          "fractal_dimension_worst"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{apply}\NormalTok{(wisc.data,}\DecValTok{2}\NormalTok{,sd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
            radius_mean            texture_mean          perimeter_mean 
           3.524049e+00            4.301036e+00            2.429898e+01 
              area_mean         smoothness_mean        compactness_mean 
           3.519141e+02            1.406413e-02            5.281276e-02 
         concavity_mean     concave.points_mean           symmetry_mean 
           7.971981e-02            3.880284e-02            2.741428e-02 
 fractal_dimension_mean               radius_se              texture_se 
           7.060363e-03            2.773127e-01            5.516484e-01 
           perimeter_se                 area_se           smoothness_se 
           2.021855e+00            4.549101e+01            3.002518e-03 
         compactness_se            concavity_se       concave.points_se 
           1.790818e-02            3.018606e-02            6.170285e-03 
            symmetry_se    fractal_dimension_se            radius_worst 
           8.266372e-03            2.646071e-03            4.833242e+00 
          texture_worst         perimeter_worst              area_worst 
           6.146258e+00            3.360254e+01            5.693570e+02 
       smoothness_worst       compactness_worst         concavity_worst 
           2.283243e-02            1.573365e-01            2.086243e-01 
   concave.points_worst          symmetry_worst fractal_dimension_worst 
           6.573234e-02            6.186747e-02            1.806127e-02 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wisc.pr }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(wisc.data, }\AttributeTok{scale =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(wisc.pr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Importance of components:
                          PC1    PC2     PC3     PC4     PC5     PC6     PC7
Standard deviation     3.6444 2.3857 1.67867 1.40735 1.28403 1.09880 0.82172
Proportion of Variance 0.4427 0.1897 0.09393 0.06602 0.05496 0.04025 0.02251
Cumulative Proportion  0.4427 0.6324 0.72636 0.79239 0.84734 0.88759 0.91010
                           PC8    PC9    PC10   PC11    PC12    PC13    PC14
Standard deviation     0.69037 0.6457 0.59219 0.5421 0.51104 0.49128 0.39624
Proportion of Variance 0.01589 0.0139 0.01169 0.0098 0.00871 0.00805 0.00523
Cumulative Proportion  0.92598 0.9399 0.95157 0.9614 0.97007 0.97812 0.98335
                          PC15    PC16    PC17    PC18    PC19    PC20   PC21
Standard deviation     0.30681 0.28260 0.24372 0.22939 0.22244 0.17652 0.1731
Proportion of Variance 0.00314 0.00266 0.00198 0.00175 0.00165 0.00104 0.0010
Cumulative Proportion  0.98649 0.98915 0.99113 0.99288 0.99453 0.99557 0.9966
                          PC22    PC23   PC24    PC25    PC26    PC27    PC28
Standard deviation     0.16565 0.15602 0.1344 0.12442 0.09043 0.08307 0.03987
Proportion of Variance 0.00091 0.00081 0.0006 0.00052 0.00027 0.00023 0.00005
Cumulative Proportion  0.99749 0.99830 0.9989 0.99942 0.99969 0.99992 0.99997
                          PC29    PC30
Standard deviation     0.02736 0.01153
Proportion of Variance 0.00002 0.00000
Cumulative Proportion  1.00000 1.00000
\end{verbatim}

The main PC result figure is called a ``score plot'' or ``PC plot'' or
``ordination plot''\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\NormalTok{wisc.pr}\SpecialCharTok{$}\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x) }\SpecialCharTok{+}
  \FunctionTok{aes}\NormalTok{(PC1,PC2, }\AttributeTok{col=}\NormalTok{diagnosis) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-14-1.pdf}}

\subsection{Questions}\label{questions-1}

\textbf{Q4. From your results, what proportion of the original variance
is captured by the first principal components (PC1)?} PC1 captures
approximately 44.3\% of the total variance in the dataset.

\textbf{Q5. How many principal components (PCs) are required to describe
at least 70\% of the original variance in the data?} At least 3
principal components (PC1-PC3) are needed to explain at least 70\% of
the variance.

\textbf{Q6. How many principal components (PCs) are required to describe
at least 90\% of the original variance in the data?} At least 7
principal components (PC1-PC7) are needed to explain at least 90\% of
the variance.

\subsection{Create Biplot}\label{create-biplot}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{biplot}\NormalTok{(wisc.pr)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-15-1.pdf}}

\textbf{Q7. What stands out to you about this plot? Is it easy or
difficult to understand? Why?} This plot is messy and difficult to
analyze.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{], }\AttributeTok{col =}\NormalTok{ diagnosis, }
     \AttributeTok{xlab =} \StringTok{"PC1"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"PC2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-16-1.pdf}}

\textbf{Q8. Generate a similar plot for principal components 1 and 3.
What do you notice about these plots}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[, }\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{)], }\AttributeTok{col =}\NormalTok{ diagnosis, }
     \AttributeTok{xlab =} \StringTok{"PC1"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"PC3"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-17-1.pdf}}

In each, there is strong clustering/less separation within the PC2 and
PC3 groups, and strong separation along the PC1.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create a data.frame for ggplot}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x)}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{diagnosis }\OtherTok{\textless{}{-}}\NormalTok{ diagnosis}

\CommentTok{\# Load the ggplot2 package}
\FunctionTok{library}\NormalTok{(ggplot2)}

\CommentTok{\# Make a scatter plot colored by diagnosis}
\FunctionTok{ggplot}\NormalTok{(df) }\SpecialCharTok{+} 
  \FunctionTok{aes}\NormalTok{(PC1, PC2, }\AttributeTok{col =}\NormalTok{ diagnosis) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-18-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pr.var }\OtherTok{\textless{}{-}}\NormalTok{ wisc.pr}\SpecialCharTok{$}\NormalTok{sdev}\SpecialCharTok{\^{}}\DecValTok{2}
\FunctionTok{head}\NormalTok{(pr.var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 13.281608  5.691355  2.817949  1.980640  1.648731  1.207357
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Variance explained by each principal component: pve}
\NormalTok{pve }\OtherTok{\textless{}{-}}\NormalTok{ pr.var }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(pr.var)}

\CommentTok{\# Plot variance explained for each principal component}
\FunctionTok{plot}\NormalTok{(pve, }\AttributeTok{xlab =} \StringTok{"Principal Component"}\NormalTok{, }
     \AttributeTok{ylab =} \StringTok{"Proportion of Variance Explained"}\NormalTok{, }
     \AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{type =} \StringTok{"o"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-20-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Alternative scree plot of the same data, note data driven y{-}axis}
\FunctionTok{barplot}\NormalTok{(pve, }\AttributeTok{ylab =} \StringTok{"Precent of Variance Explained"}\NormalTok{,}
     \AttributeTok{names.arg=}\FunctionTok{paste0}\NormalTok{(}\StringTok{"PC"}\NormalTok{,}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(pve)), }\AttributeTok{las=}\DecValTok{2}\NormalTok{, }\AttributeTok{axes =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{axis}\NormalTok{(}\DecValTok{2}\NormalTok{, }\AttributeTok{at=}\NormalTok{pve, }\AttributeTok{labels=}\FunctionTok{round}\NormalTok{(pve,}\DecValTok{2}\NormalTok{)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-21-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# ggplot based graph}
\CommentTok{\#install.packages("factoextra")}
\FunctionTok{library}\NormalTok{(factoextra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_eig}\NormalTok{(wisc.pr, }\AttributeTok{addlabels =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in geom_bar(stat = "identity", fill = barfill, color = barcolor, :
Ignoring empty aesthetic: `width`.
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-22-1.pdf}}

\textbf{Q9.For the first principal component, what is the component of
the loading vector (i.e.~wisc.pr\$rotation{[},1{]}) for the feature
concave.points\_mean?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wisc.pr}\SpecialCharTok{$}\NormalTok{rotation[}\StringTok{"concave.points\_mean"}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] -0.2608538
\end{verbatim}

The loading of the concave.points\_mean on PC1 is approximately
\texttt{wisc.pr\$rotation{[}"concave.points\_mean",\ 1{]}}. So, higher
values of concave.points\_mean correspond to lower PC1 scores. PC1
separates malignant and benign cases, helping to distinguish them.

\textbf{Q10. What is the minimum number of principal components required
to explain 80\% of the variance of the data?} To explain at least 80\%
of the total variance, 4 principal components (PC1-PC\$) is needed.

\section{Hierarchical clustering}\label{hierarchical-clustering}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scale the wisc.data data using the "scale()" function}
\NormalTok{data.scaled }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(wisc.data)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data.dist }\OtherTok{\textless{}{-}} \FunctionTok{dist}\NormalTok{(data.scaled)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wisc.hclust }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(data.dist, }\AttributeTok{method =} \StringTok{"complete"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Results of Hierarchical
Clustering}\label{results-of-hierarchical-clustering}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(wisc.hclust)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{20}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-27-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(}\FunctionTok{cutree}\NormalTok{(wisc.hclust,}\AttributeTok{k=}\DecValTok{4}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

  1   2   3   4 
177   7 383   2 
\end{verbatim}

This looks terrible.

\textbf{Q11. Using the plot() and abline() functions, what is the height
at which the clustering model has 4 clusters?} The height at which 4
clusters occur is 20.

\subsection{Selecting number of
clusters}\label{selecting-number-of-clusters}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cut the dendrogram into 4 clusters}
\NormalTok{wisc.hclust.clusters }\OtherTok{\textless{}{-}} \FunctionTok{cutree}\NormalTok{(wisc.hclust, }\AttributeTok{k =} \DecValTok{4}\NormalTok{)}

\CommentTok{\# Compare cluster assignments to actual diagnoses}
\FunctionTok{table}\NormalTok{(wisc.hclust.clusters, diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                    diagnosis
wisc.hclust.clusters   B   M
                   1  12 165
                   2   2   5
                   3 343  40
                   4   0   2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (k }\ControlFlowTok{in} \DecValTok{2}\SpecialCharTok{:}\DecValTok{10}\NormalTok{) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Number of clusters:"}\NormalTok{, k, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{table}\NormalTok{(}\FunctionTok{cutree}\NormalTok{(wisc.hclust, }\AttributeTok{k =}\NormalTok{ k), diagnosis))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Number of clusters: 2 
   diagnosis
      B   M
  1 357 210
  2   0   2

Number of clusters: 3 
   diagnosis
      B   M
  1 355 205
  2   2   5
  3   0   2

Number of clusters: 4 
   diagnosis
      B   M
  1  12 165
  2   2   5
  3 343  40
  4   0   2

Number of clusters: 5 
   diagnosis
      B   M
  1  12 165
  2   0   5
  3 343  40
  4   2   0
  5   0   2

Number of clusters: 6 
   diagnosis
      B   M
  1  12 165
  2   0   5
  3 331  39
  4   2   0
  5  12   1
  6   0   2

Number of clusters: 7 
   diagnosis
      B   M
  1  12 165
  2   0   3
  3 331  39
  4   2   0
  5  12   1
  6   0   2
  7   0   2

Number of clusters: 8 
   diagnosis
      B   M
  1  12  86
  2   0  79
  3   0   3
  4 331  39
  5   2   0
  6  12   1
  7   0   2
  8   0   2

Number of clusters: 9 
   diagnosis
      B   M
  1  12  86
  2   0  79
  3   0   3
  4 331  39
  5   2   0
  6  12   0
  7   0   2
  8   0   2
  9   0   1

Number of clusters: 10 
    diagnosis
       B   M
  1   12  86
  2    0  59
  3    0   3
  4  331  39
  5    0  20
  6    2   0
  7   12   0
  8    0   2
  9    0   2
  10   0   1
\end{verbatim}

\textbf{Q12. Can you find a better cluster vs diagnoses match by cutting
into a different number of clusters between 2 and 10?} Cutting the
dendrogram into 4 clusters gives the best match to the true diagnoses.
One cluster is mostly malignant, the other is mostly benign. Fewer
clusters mix the two groups, and does not improve separation.

\textbf{Q13. Which method gives your favorite results for the same
data.dist dataset? Explain your reasoning.} The ward.D2 method gives my
preferred result. It creates clearer, interpretable groupings for this
dataset.

\section{K-means Clustering}\label{k-means-clustering}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create a k{-}means model with 2 clusters, scaled data, and 20 random starts}
\NormalTok{wisc.km }\OtherTok{\textless{}{-}} \FunctionTok{kmeans}\NormalTok{(}\FunctionTok{scale}\NormalTok{(wisc.data), }\AttributeTok{centers =} \DecValTok{2}\NormalTok{, }\AttributeTok{nstart =} \DecValTok{20}\NormalTok{)}

\CommentTok{\# Compare k{-}means cluster membership to actual diagnoses}
\FunctionTok{table}\NormalTok{(wisc.km}\SpecialCharTok{$}\NormalTok{cluster, diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   diagnosis
      B   M
  1 343  37
  2  14 175
\end{verbatim}

\textbf{Q14. How well does k-means separate the two diagnoses? How does
it compare to your hclust results?} K-means clustering separates the two
diagnoses very well. Cluster 1 is mostly malignant and cluster 2 is
mostly benign. K-means clustering is better at distinguishing clusters
compared to hierarchical clustering.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compare k{-}means clusters to hierarchical clustering clusters}
\FunctionTok{table}\NormalTok{(wisc.hclust.clusters, wisc.km}\SpecialCharTok{$}\NormalTok{cluster)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                    
wisc.hclust.clusters   1   2
                   1  17 160
                   2   0   7
                   3 363  20
                   4   0   2
\end{verbatim}

\section{Combining Methods}\label{combining-methods}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Use first 7 PCs (≥90\% variance)}
\NormalTok{wisc.pr.hclust }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(}\FunctionTok{dist}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{7}\NormalTok{]), }\AttributeTok{method =} \StringTok{"ward.D2"}\NormalTok{)}

\CommentTok{\# Visualize}
\FunctionTok{plot}\NormalTok{(wisc.pr.hclust)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-32-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{grps }\OtherTok{\textless{}{-}} \FunctionTok{cutree}\NormalTok{(wisc.pr.hclust, }\AttributeTok{k=}\DecValTok{2}\NormalTok{)}
\FunctionTok{table}\NormalTok{(grps)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
grps
  1   2 
216 353 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(grps, diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    diagnosis
grps   B   M
   1  28 188
   2 329  24
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{], }\AttributeTok{col=}\NormalTok{grps)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-35-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{], }\AttributeTok{col=}\NormalTok{diagnosis)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-36-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(grps)}
\FunctionTok{levels}\NormalTok{(g)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "1" "2"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g }\OtherTok{\textless{}{-}} \FunctionTok{relevel}\NormalTok{(g,}\DecValTok{2}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(g)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "2" "1"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot using our re{-}ordered factor }
\FunctionTok{plot}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{], }\AttributeTok{col=}\NormalTok{g)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-39-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rgl)}
\FunctionTok{plot3d}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{], }\AttributeTok{xlab=}\StringTok{"PC 1"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"PC 2"}\NormalTok{, }\AttributeTok{zlab=}\StringTok{"PC 3"}\NormalTok{, }\AttributeTok{cex=}\FloatTok{1.5}\NormalTok{, }\AttributeTok{size=}\DecValTok{1}\NormalTok{, }\AttributeTok{type=}\StringTok{"s"}\NormalTok{, }\AttributeTok{col=}\NormalTok{grps)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wisc.pr.hclust }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(}\FunctionTok{dist}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{7}\NormalTok{]), }\AttributeTok{method =} \StringTok{"ward.D2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Interactive 3D PCA plot (HTML only)}
\FunctionTok{library}\NormalTok{(rgl)}

\CommentTok{\# color by diagnosis }
\NormalTok{grps }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(diagnosis }\SpecialCharTok{==} \StringTok{"M"}\NormalTok{, }\StringTok{"red"}\NormalTok{, }\StringTok{"blue"}\NormalTok{)}

\FunctionTok{plot3d}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{],}
       \AttributeTok{xlab =} \StringTok{"PC 1"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"PC 2"}\NormalTok{, }\AttributeTok{zlab =} \StringTok{"PC 3"}\NormalTok{,}
       \AttributeTok{cex =} \FloatTok{1.5}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{, }\AttributeTok{type =} \StringTok{"s"}\NormalTok{, }\AttributeTok{col =}\NormalTok{ grps)}

\FunctionTok{rglwidget}\NormalTok{(}\AttributeTok{width =} \DecValTok{400}\NormalTok{, }\AttributeTok{height =} \DecValTok{400}\NormalTok{)  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
file:////private/var/folders/dy/66l3lnns1tx9v_6vw2blqsrw0000gn/T/Rtmp3wkU7A/fileb4f0144163b4.html screenshot completed
\end{verbatim}

\includegraphics[width=1.33in,height=\textheight,keepaspectratio]{../../../../../../private/var/folders/dy/66l3lnns1tx9v_6vw2blqsrw0000gn/T/Rtmp3wkU7A/fileb4f0317d395e.png}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Use the distance along the first 7 PCs for clustering}
\NormalTok{wisc.pr.hclust }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(}\FunctionTok{dist}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{7}\NormalTok{]), }\AttributeTok{method =} \StringTok{"ward.D2"}\NormalTok{)}

\CommentTok{\# Cut into 2 clusters}
\NormalTok{wisc.pr.hclust.clusters }\OtherTok{\textless{}{-}} \FunctionTok{cutree}\NormalTok{(wisc.pr.hclust, }\AttributeTok{k =} \DecValTok{2}\NormalTok{)}

\CommentTok{\# Compare PCA{-}based hierarchical clusters to actual diagnoses}
\FunctionTok{table}\NormalTok{(wisc.pr.hclust.clusters, diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                       diagnosis
wisc.pr.hclust.clusters   B   M
                      1  28 188
                      2 329  24
\end{verbatim}

\textbf{Q15. How well does the newly created model with four clusters
separate out the two diagnoses?} The PCA-based hierarchical clustering
with 2 clusters separates the diagnoses well. Cluster 1 is mostly
malignant, and cluster 2 is mostly benign.

\textbf{Q16. How well do the k-means and hierarchical clustering models
you created in previous sections (i.e.~before PCA) do in terms of
separating the diagnoses? Again, use the table() function to compare the
output of each model (wisc.km\$cluster and wisc.hclust.clusters) with
the vector containing the actual diagnoses.} K-means shows cleaner, more
distinct clusters, while hierarchical clustering produces reasonable but
less consistent grouping.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compare k{-}means model clusters to actual diagnoses}
\FunctionTok{table}\NormalTok{(wisc.km}\SpecialCharTok{$}\NormalTok{cluster, diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   diagnosis
      B   M
  1 343  37
  2  14 175
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compare hierarchical clustering model clusters (before PCA) to actual diagnoses}
\FunctionTok{table}\NormalTok{(wisc.hclust.clusters, diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                    diagnosis
wisc.hclust.clusters   B   M
                   1  12 165
                   2   2   5
                   3 343  40
                   4   0   2
\end{verbatim}

Clustering the original data was not very productive. The PCA results
looked promising. Here we combine these methods by clustering from our
PCA results. In other words ``clustering in PC space''\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# take the first 3 PCs}
\NormalTok{dist.pc }\OtherTok{\textless{}{-}} \FunctionTok{dist}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{])}
\NormalTok{wisc.pr.hclust }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(dist.pc, }\AttributeTok{method=}\StringTok{"ward.D2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

View the tree\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(wisc.pr.hclust)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h=}\DecValTok{70}\NormalTok{, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-46-1.pdf}}

To get our clustering membership vector (i.e.~our main clustering
result) we ``cut'' the tree at a desired height or to yield a desired
number of ``k'' groups.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{grps }\OtherTok{\textless{}{-}} \FunctionTok{cutree}\NormalTok{(wisc.pr.hclust, }\AttributeTok{k=}\DecValTok{2}\NormalTok{)}
\FunctionTok{table}\NormalTok{(grps)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
grps
  1   2 
203 366 
\end{verbatim}

How does this clustering grps compare to the expert diagnosis

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(grps, diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    diagnosis
grps   B   M
   1  24 179
   2 333  33
\end{verbatim}

\subsection{Sensitivity/Specificity}\label{sensitivityspecificity}

\textbf{Q17. Which of your analysis procedures resulted in a clustering
model with the best specificity? How about sensitivity?}

High Specificity: The PCA-based hierarchical clustering model corrently
classifies most benign samples (329 B, 24 M) high TN rate / fewer false
positives.

High Sensitivity: The k-means model captures the majority of malignant
samples (175 M, 14 B) high TP rate / fewer false negatives.

\section{Prediction}\label{prediction}

We can use our PCA model for prediction with new input patient samples.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load new data}
\NormalTok{url }\OtherTok{\textless{}{-}} \StringTok{"https://tinyurl.com/new{-}samples{-}CSV"}
\NormalTok{new }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(url)}

\CommentTok{\# Project new samples into the PCA space}
\NormalTok{npc }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(wisc.pr, }\AttributeTok{newdata =}\NormalTok{ new)}

\CommentTok{\# Visualize}
\FunctionTok{plot}\NormalTok{(wisc.pr}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{], }\AttributeTok{col =}\NormalTok{ g)             }\CommentTok{\# original PCA points (colored by diagnosis)}
\FunctionTok{points}\NormalTok{(npc[,}\DecValTok{1}\NormalTok{], npc[,}\DecValTok{2}\NormalTok{], }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{, }\AttributeTok{cex =} \DecValTok{3}\NormalTok{)  }\CommentTok{\# new samples}
\FunctionTok{text}\NormalTok{(npc[,}\DecValTok{1}\NormalTok{], npc[,}\DecValTok{2}\NormalTok{], }\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{), }\AttributeTok{col =} \StringTok{"white"}\NormalTok{)              }\CommentTok{\# label samples}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{mini-project_files/figure-pdf/unnamed-chunk-49-1.pdf}}

\textbf{Q18. Which of these new patients should we prioritize for follow
up based on your results?} Patient 2's sample pattern is more consistent
with malignant characteristics and should be prioritized for clinical
evaluation.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sessionInfo}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
R version 4.5.1 (2025-06-13)
Platform: aarch64-apple-darwin20
Running under: macOS Sequoia 15.3.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgl_1.3.24       factoextra_1.0.7 ggplot2_4.0.0   

loaded via a namespace (and not attached):
 [1] generics_0.1.4     tidyr_1.3.1        rstatix_0.7.2      digest_0.6.37     
 [5] magrittr_2.0.4     evaluate_1.0.5     grid_4.5.1         RColorBrewer_1.1-3
 [9] fastmap_1.2.0      jsonlite_2.0.0     processx_3.8.6     ggrepel_0.9.6     
[13] backports_1.5.0    chromote_0.5.1     Formula_1.2-5      ps_1.9.1          
[17] promises_1.4.0     purrr_1.1.0        scales_1.4.0       abind_1.4-8       
[21] cli_3.6.5          rlang_1.1.6        base64enc_0.1-3    withr_3.0.2       
[25] yaml_2.3.10        otel_0.2.0         tools_4.5.1        ggsignif_0.6.4    
[29] dplyr_1.1.4        ggpubr_0.6.1       broom_1.0.10       png_0.1-8         
[33] vctrs_0.6.5        R6_2.6.1           lifecycle_1.0.4    car_3.1-3         
[37] htmlwidgets_1.6.4  pkgconfig_2.0.3    pillar_1.11.1      later_1.4.4       
[41] gtable_0.3.6       glue_1.8.0         Rcpp_1.1.0         xfun_0.53         
[45] tibble_3.3.0       tidyselect_1.2.1   rstudioapi_0.17.1  knitr_1.50        
[49] farver_2.1.2       websocket_1.4.4    htmltools_0.5.8.1  rmarkdown_2.30    
[53] carData_3.0-5      labeling_0.4.3     webshot2_0.1.2     compiler_4.5.1    
[57] S7_0.2.0          
\end{verbatim}




\end{document}
